from enum import Enum

SLOTS = Enum('SLOTS',[('FLOWER',"Flower"),('FEATHER',"Feather"),('SANDS',"Sands"),('GOBLET',"Goblet"),('CIRCLET',"Circlet")])
SUBMAIN_STATS_NAMES = Enum('STAT_NAMES',[('HP',"HP"),('HP_P',"HP%"),('ATK',"ATK"),('ATK_P',"ATK%"),('DEF',"DEF"),('DEF_P',"DEF%"),('ER',"ER"),('EM',"EM"),('PYRO',"Pyro"),('ELECTRO',"Electro"),('CRYO',"Cryo"),('HYDRO',"Hydro"),('DENDRO',"Dendro"),('ANEMO',"Anemo"),('GEO',"Geo"),('PHYSICAL',"Physical"),('HEALING',"Healing"),('CD',"CritDmg"),('CR',"Crit%")])

MAIN_STAT_PROBABILITY = {
    SLOTS.FLOWER : {SUBMAIN_STATS_NAMES.HP: 1},
    SLOTS.FEATHER : {SUBMAIN_STATS_NAMES.ATK: 1},
    SLOTS.SANDS : {SUBMAIN_STATS_NAMES.HP_P: 0.2668, SUBMAIN_STATS_NAMES.ATK_P: 0.2666, SUBMAIN_STATS_NAMES.DEF_P: 0.2666, SUBMAIN_STATS_NAMES.ER: 0.1, SUBMAIN_STATS_NAMES.EM: 0.1},
    SLOTS.GOBLET : {SUBMAIN_STATS_NAMES.HP_P: 0.1925, SUBMAIN_STATS_NAMES.ATK_P: 0.1925, SUBMAIN_STATS_NAMES.DEF_P: 0.19, SUBMAIN_STATS_NAMES.PYRO: 0.05, SUBMAIN_STATS_NAMES.ELECTRO: 0.05, SUBMAIN_STATS_NAMES.CRYO: 0.05,
               SUBMAIN_STATS_NAMES.HYDRO: 0.05, SUBMAIN_STATS_NAMES.DENDRO: 0.05, SUBMAIN_STATS_NAMES.ANEMO: 0.05, SUBMAIN_STATS_NAMES.GEO: 0.05, SUBMAIN_STATS_NAMES.PHYSICAL: 0.05, SUBMAIN_STATS_NAMES.EM: 0.025},
    SLOTS.CIRCLET : {SUBMAIN_STATS_NAMES.HP_P: 0.22, SUBMAIN_STATS_NAMES.ATK_P: 0.22, SUBMAIN_STATS_NAMES.DEF_P: 0.22, SUBMAIN_STATS_NAMES.CR: 0.1, SUBMAIN_STATS_NAMES.CD: 0.1, SUBMAIN_STATS_NAMES.HEALING: 0.1, SUBMAIN_STATS_NAMES.EM: 0.04}
}

ARTIFACT_SOURCE = Enum('ARTIFACT_SOURCE',[('DOMAIN',"Domain"),('STRONGBOX',"Strongbox")])

NUM_OF_SUBSTATS_PROBABILITIES = {
    ARTIFACT_SOURCE.DOMAIN: {3: 0.8, 4: 0.2},
    ARTIFACT_SOURCE.STRONGBOX: {3: 0.66, 4: 0.34}
}

SUBSTAT_WEIGHTS = {SUBMAIN_STATS_NAMES.HP: 6, SUBMAIN_STATS_NAMES.ATK: 6, SUBMAIN_STATS_NAMES.DEF: 6, SUBMAIN_STATS_NAMES.HP_P: 4, SUBMAIN_STATS_NAMES.ATK_P: 4, SUBMAIN_STATS_NAMES.DEF_P: 4, SUBMAIN_STATS_NAMES.ER: 4, SUBMAIN_STATS_NAMES.EM: 4, SUBMAIN_STATS_NAMES.CR: 3, SUBMAIN_STATS_NAMES.CD: 3}
SUBSTAT_MAX_ROLLS = {SUBMAIN_STATS_NAMES.HP: 298.75, SUBMAIN_STATS_NAMES.ATK: 19.45, SUBMAIN_STATS_NAMES.DEF: 23.15, SUBMAIN_STATS_NAMES.HP_P: 5.83, SUBMAIN_STATS_NAMES.ATK_P: 5.83, SUBMAIN_STATS_NAMES.DEF_P: 7.29, SUBMAIN_STATS_NAMES.EM: 23.31,
                     SUBMAIN_STATS_NAMES.ER: 6.48, SUBMAIN_STATS_NAMES.CR: 3.89, SUBMAIN_STATS_NAMES.CD: 7.77}


